server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trade?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
app:
  microservice:
    portfolio:
      endpoints:
        asset: http://PORTFOLIO-INTERNAL-MS/portfolio/asset