spring:
  datasource:
    username: ${database_username}
    password: ${database_password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  profiles:
    active: ${ENV}
  application:
    name: TRADE-INTERNAL-MS

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - health
          - info

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost