spring:
  application:
    name: TRADE-INTERNAL-MS
  datasource:
    username: ${database_username}
    password: ${database_password}
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
      show-sql: true
  profiles:
    active: ${ENV}
  config:
    import: configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:9196}

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - health
          - info